ticket_pattern = "#([A-Z]+-\\d+)"
git_author_pattern = "Florin Ciurcanu"
daily_target = 8
daily_meeting = ["SOOL-289", 0.25]
# daily_meeting = ["DATAU-25", 0.25]
skip_days = [
    "2024-05-01",
    "2024-05-03",
    "2024-05-06",
    "2024-06-24",
    "2024-08-15..2024-08-23"
]
weeks_behind = 7
repositories = [
    "../../work/partner-portal/",
    "../../work/configurator-api/",
    "../../work/configurator-www",
    "../../work/soolutions-infra/",
    # "../../work/infrau/",
    # "../../work/proxyu/",
    # "../../work/nodeu/",
    # "../../work/idu/",
    # "../../work/cau/",
]

ignore_file_pattern = "(json|mov|ignore|png|ico|xlsx|po|excalidraw)$"

[jira]
server = "https://jibecompany.atlassian.net"

[slack]
# channel = "C076SDUBV63"  # checkmeout
channel = "C02JWQA5AGK"  # soolutions

